version: '3'

services:
  postgres:
    image: postgres:alpine3.20
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB= admindb
    ports:
      - "5432:5432"
    volumes:
      - ./data/docker-volumes/postgres:/var/lib/postgresql/data
    networks_mode: "host"

  golang-app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    network_mode: "host"
    depends_on:
      - postgres